# Constantes
PLAYER_ONE_STUDENT = 1
PLAYER_ONE_MASTER = 2
PLAYER_TWO_STUDENT = 3
PLAYER_TWO_MASTER = 4
EMPTY_CELL = 0

PLAYER_ONE_POSITION = 1
PLAYER_TWO_POSITION = 2

PLAYER_ONE_TEMPLE = (2, 4)
PLAYER_TWO_TEMPLE = (2, 0)

COLOR_RED = 1
COLOR_BLUE = 2

STR_MAPPING = {
    PLAYER_ONE_STUDENT: 'x',
    PLAYER_ONE_MASTER: 'X',
    PLAYER_TWO_STUDENT: 'o',
    PLAYER_TWO_MASTER: 'O',
    EMPTY_CELL: '-'
}

COLOR_MAPPING = {
    COLOR_RED: PLAYER_ONE_POSITION,
    COLOR_BLUE: PLAYER_TWO_POSITION
}
